export const SET_SHOWS_LIST = 'SET_SHOWS_LIST';
export const CLEAR_SHOWS_LIST = 'CLEAR_SHOWS_LIST';

export const SET_CURRENT_SHOW = 'SET_CURRENT_SHOW';
export const CLEAR_CURRENT_SHOW = 'CLEAR_CURRENT_SHOW';

export const SET_CURRENT_SHOW_EPISODES = 'SET_CURRENT_SHOW_EPISODES';

export const SET_CURRENT_EPISODE = 'SET_CURRENT_EPISODE';
export const CLEAR_CURRENT_EPISODE = 'CLEAR_CURRENT_EPISODE';


